- platform: template
  name: "Follow Me"
  id: follow_me
  optimistic: true
  restore_mode: RESTORE_DEFAULT_OFF

- platform: template
  name: "Sleep Mode"
  id: sleep_mode_switch
  optimistic: true
  turn_on_action:
    - lambda: |-
        if (id(first_boot)) {
          return;
        }
        id(unit_mode_flags_bytes) |= 0x01;
        id(new_input) = true;
  turn_off_action:
    - lambda: |-
        if (id(first_boot)) {
          return;
        }
        id(unit_mode_flags_bytes) &= ~0x01;
        id(new_input) = true;
